export const data = [
    {
       "Title":"UPPSC Technical Education Teaching Service Form Status 2021 / Re Upload Photo Signature",
       "examComissioon":"Uttar Pradesh Public Service Commission (UPPSC)",
       "subtitle":"UP Technical Education Teaching Form Status / Re Upload Photo / Signature Online.",
       "advtNo":"Advt No. : A-7/E-1/2021 Short Details of Notification",
       "impDate1":"22/10/2021",
       "impDate2":"29/10/2021",
       "impdate3":"Last Date Re Upload Photo / Signature Only for Objected Candidates : 29/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"No Application Fee For the Check UPPSC Status OR Re Upload Photo Signature.",
       "examName":"UPPSC Technical Education Various Post Exam 2021",
       "noOfPost":"1370",
       "egligible":"Candidate Who Are Registered Between 15/09/2021 to 15/10/2021 Are Eligible to Check the Status.",
       "linkFirst":"Click Here",
       "link2":"https://uppsc.up.nic.in/ViewStatus.aspx",
       "link3":"Click Here",
       "link4":"https://www.sarkariresult.com/2021/uppsc-technical-edu-service-sep21/",
       "link5":"Click Here",
       "officialweb":"https://uppsc.up.nic.in/"
    },
    {
       "Title":"UPPSC Agriculture Services Mains Exam 2020 Online Form 2021",
       "examComissioon":"",
       "subtitle":"UP Combined State Agriculture Services (MAIN) Exam Online Form",
       "advtNo":"Advt No. : A-4/E-1/2020 Short Details of Notification",
       "impDate1":"22/10/2021",
       "impDate2":"03/11/2021",
       "impdate3":"Pay Exam Fee Last Date : 03/11/2021",
       "genrealFEE":"General / OBC : 225/-",
       "scstFee":"SC / ST : 125/-",
       "fee3":"PH Candidates : 25/-",
       "examName":"UPPSC Agriculture Services Various Post Mains Exam 2021",
       "noOfPost":"564",
       "egligible":"Qualified in the Combined State Agriculture Services (Pre.) Exam conducted by the Uttar Pradesh Public Service Commission which was held on 01 August 2021.",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://uppsc.up.nic.in/View_Notices.aspx?ID=news&N=1983",
       "link5":"Click Here",
       "officialweb":"https://t.me/sarkari"
    },
    {
       "Title":"High Court Allahabad Review Officer (Samiksha Adhikari) Exam Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"22/10/2021",
       "impDate2":"11/11/2021",
       "impdate3":"Pay Exam Fee Last Date : 12/11/2021",
       "genrealFEE":"General / OBC : 800/-",
       "scstFee":"SC / ST : 600/-",
       "fee3":"Pay the Exam Fee Through Debit Card, Credit Card, Net Banking Only.",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"NHM UP Staff Nurse Online Form 2021",
       "examComissioon":"National Health Mission, Uttar Pradesh (NHM, UP)",
       "subtitle":"",
       "advtNo":"Advt No. : 588/SPMU/NHM/2021-22/4151 Short Details of Notification",
       "impDate1":": 21/10/2021 ",
       "impDate2":"",
       "impdate3":"Exam Date : Notified Soon",
       "genrealFEE":"General / OBC / EWS : 0/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"No Application Fee for the All Candidates Only Registered Online.",
       "examName":"Post Name",
       "noOfPost":"Total Post\n",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"AIIMS NORCET 2021 Exams Online Form",
       "examComissioon":"All India Institute of Medical Science (AIIMS)",
       "subtitle":"",
       "advtNo":"Advt No. : 149/2021 Short Details of Notification",
       "impDate1":"16/10/2021",
       "impDate2":"30/10/2021 upto 05:00 PM only",
       "impdate3":"Fee Payment Last Date : 30/10/2021",
       "genrealFEE":"General / OBC : 3000/-",
       "scstFee":"SC / ST / EWS : 2500/-",
       "fee3":"PH : 0/- (Exempted)",
       "examName":"Post Name",
       "noOfPost":"Eligibility",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Rajasthan State Industrial Development and Investment Corp. Ltd. RIICO Various Post Exam Online Form 2021",
       "examComissioon":"Rajasthan State Industrial Development and Investment Corp. Ltd. (RIICO) ",
       "subtitle":"",
       "advtNo":"Advt No. : A.1(8)378/2020 Batch Short Details of Notification",
       "impDate1":"17/10/2021",
       "impDate2":" 13/11/2021",
       "impdate3":"Pay Exam Fee Last Date : 13/11/2021",
       "genrealFEE":"For Draughtsman & Junior Assistant Post:",
       "scstFee":"General : 700/-",
       "fee3":"OBC / EWS : 525/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"IBPS PO XI Exam Online Form 2021 for 4135 Post",
       "examComissioon":"Institute Of Banking Personal Selection (IBPS)",
       "subtitle":"",
       "advtNo":"CRP PO/MT XI Short Details of Notification",
       "impDate1":" : 20/10/2021",
       "impDate2":"",
       "impdate3":"Pay Exam Fee Last Date : 10/11/2021",
       "genrealFEE":"General / OBC : 850/-",
       "scstFee":"SC / ST / PH : 175/-",
       "fee3":"Pay the Examination Fee Through Online Fee Mode Debit Card, Credit Card, Net Banking, Mobile Banking, E Wallet, Cash Card, IMPS and E Challan Fee Mode",
       "examName":"Probationary Officer PO / Management Trainee MT XI",
       "noOfPost":"4135",
       "egligible":"",
       "linkFirst":"Click Here",
       "link2":"https://ibpsonline.ibps.in/crppo11jul21/",
       "link3":"Click Here",
       "link4":"https://www.rojgarresult.com/imgresize/index/",
       "link5":"Click Here",
       "officialweb":"https://www.sarkariresults.org.in/wp-content/uploads/2021/10/ibpspo11-scaled.jpg"
    },
    {
       "Title":"IIT Kanpur Various Post Online Form 2021",
       "examComissioon":"Indian Institute of Kanpur, IITK",
       "subtitle":"",
       "advtNo":"IITK Advt No. : 01/2021 Short Details of Notification",
       "impDate1":"October 2021",
       "impDate2":" 16/11/2021 upto 05 PM",
       "impdate3":"Pay Exam Fee Last Date : 16/11/2021",
       "genrealFEE":"Group A Post Gen/OBC/EWS : 500/-",
       "scstFee":"Group B & C Post Gen/OBC/EWS : : 250/-",
       "fee3":"SC / ST / PH : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Join Indian Navy 10+2 Sailor Entry SSR / AA February 2022 Batch Online Form 2021",
       "examComissioon":"The Indian Navy (Nausena Bharti)",
       "subtitle":"",
       "advtNo":"SSR / AA February 2022 Batch Short Details of Notification",
       "impDate1":"16/10/2021",
       "impDate2":"",
       "impdate3":"Complete Form Last Date : 25/10/2021",
       "genrealFEE":"General / OBC : 0",
       "scstFee":"SC / ST : 0/-\n",
       "fee3":"No Application Fee for the All Candidates Only Registration Online.",
       "examName":"Senior Secondary Recruit (SSR) February 2022 Batch",
       "noOfPost":"2000",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Haryana FCI Watchman Exam Online Form 2021",
       "examComissioon":"Food Corporation of India (FCI)",
       "subtitle":"FCI Haryana Category IV Watchman Recruitment 2021 Online Form",
       "advtNo":"FCI Haryana 2021 Short Details of Notification",
       "impDate1":"20/10/2021",
       "impDate2":"19/11/2021",
       "impdate3":"Last Date Pay Exam Fee : 19/11/2021",
       "genrealFEE":"General / OBC : 250/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://fciharyana-watch-ward.in/login",
       "link5":"Click Here",
       "officialweb":"https://documents.fciharyana-watch-ward.in/notification"
    },
    {
       "Title":"NCR Allahabad RRC Prayagraj Act Apprentice Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Advt No. : RRC/NCR/02/2021 Short Details of Notification",
       "impDate1":"02/11/2021",
       "impDate2":" 01/12/2021",
       "impdate3":"Pay Exam Fee Last Date : 01/12/2021",
       "genrealFEE":"General / OBC / EWS: 100/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttar Pradesh UPPCL Camp Assistant Grade 3 Online Form 2021",
       "examComissioon":"Uttar Pradesh Power Corporation Limited UPPCL",
       "subtitle":"",
       "advtNo":"Advt No. : 04/VSA/2021 Short Details of Notification",
       "impDate1":"13/10/2021",
       "impDate2":"09/11/2021",
       "impdate3":"Last Date Fee Payment : 09/11/2021",
       "genrealFEE":"General / OBC / EWS : 1180/-",
       "scstFee":"SC / ST : 826/-",
       "fee3":"PH (Divyang) : 12/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here ",
       "link4":"https://cdn.digialm.com/EForms/configuredHtml/1258/73758/Instruction.html",
       "link5":"Click Here ",
       "officialweb":"https://www.youtube.com/watch?v=bpeZ8ZJ8_iY"
    },
    {
       "Title":"RRC WCR Kota, Jabalpur, Bhopal Railway Act Trade Apprentice Online Form 2021.",
       "examComissioon":"West Central Railway WCR, Jabalpur",
       "subtitle":"",
       "advtNo":"02/2021 Act Apprentice Short Details of Notification",
       "impDate1":"11/10/2021",
       "impDate2":"10/11/2021",
       "impdate3":"Complete Form Last Date : 10/11/2021",
       "genrealFEE":"General / OBC : 100/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Navy Matric Recruit MR Online Form Online Form 2021",
       "examComissioon":"Join Indian Navy (Nausena Bharti)",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"",
       "impDate2":"02/11/2021",
       "impdate3":"Last Date Complete Form : 02/11/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"No Application Fee For the Indian Navy MR Sailor Entry 2022. Only Registered Online.",
       "examName":"Chef",
       "noOfPost":"",
       "egligible":"Age Between : 01/04/2002 to 31/03/2005",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"AMD Recruitment 2021 for UDC, Driver, Security Guard, Scientific Assistant & Technical Post Online Form 2021.",
       "examComissioon":"Atomic Minerals Directorate for Exploration and Research",
       "subtitle":"AMD Recruitment 2021 UDC, Driver & Other Various Post Online Form 2021",
       "advtNo":"Advt No. : AMD-3/2021 Short Details of Notification",
       "impDate1":"09/10/2021",
       "impDate2":" 24/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 24/10/2021",
       "genrealFEE":"For Scientific Assistant Post : ",
       "scstFee":"General / OBC / EWS: 200/-",
       "fee3":"SC / ST / PH / Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"RRC ECR Railway Various Trade Apprentice Online Form 2021.",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":" RRC/ECR/HRD/ACT.App./2021-22 Short Details of Notification",
       "impDate1":"06/10/2021",
       "impDate2":"05/11/2021 Upto 05 PM",
       "impdate3":"Pay Exam Fee Last Date : 05/11/2021",
       "genrealFEE":"General / OBC / EWS: 100/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Gen",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Join Indian Army NCC 51th Special Entry (April 2022 Batch) Online Form 2021",
       "examComissioon":"Indian Army 51 NCC Special Entry Men & Women Recruitment 2021",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"",
       "impDate2":" 03/11",
       "impdate3":"Last Date Complete Form : 03/11/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / Female : 0/-",
       "fee3":"No Application Fee for the All Candidates Only Fill the Online Application Form",
       "examName":"NCC MEN 49 Entry",
       "noOfPost":"50",
       "egligible":"Bachelor Degree in Any Stream with Minimum 50% Marks.",
       "linkFirst":"Click Here",
       "link2":"http://joinindianarmy.nic.in/login.htm",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Food Safety and Standard Authority of India (FSSAI) Various Post Online Form 2021",
       "examComissioon":"Food Safety and Standard Authority of India (FSSAI)",
       "subtitle":"",
       "advtNo":"Advt NO. : 02-04/2021 Short Details of Notification",
       "impDate1":": 13/10/2021",
       "impDate2":"",
       "impdate3":"Pay Exam Fee Last Date: 12/11/2021",
       "genrealFEE":"General / OBC / EWS : 1500/-",
       "scstFee":"SC / ST / PH : 500/-",
       "fee3":"All Category Female : 500/-",
       "examName":"Assistant",
       "noOfPost":"30",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"State Bank of India SBI Probationary Officer PO Recruitment 2021 Online Form ",
       "examComissioon":"State Bank of India (SBI)",
       "subtitle":"SBI Probationary Officers PO Recruitment 2021 Online Form",
       "advtNo":"Advt No. : CRPD/ PO/ 2021-22/18 Short Details of Notification",
       "impDate1":"05/10/2021",
       "impDate2":"25/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 25/10/2021",
       "genrealFEE":"General / OBC / EWS : 750/-",
       "scstFee":"SC / ST / PH: 0/-",
       "fee3":"Pay the Examination Fee Through Online Fee Mode Debit Card, Credit Card, Net Banking Only.  ",
       "examName":"Vacancy Type",
       "noOfPost":"Gen",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://www.sbi.co.in/documents/77530/11154687/041021-Final+Advertisement+PO+21-22.pdf/61eb5452-c5e8-e057-e460-1e89486812d8?t=1633349820829",
       "link5":"Click Here",
       "officialweb":"https://t.me/sarkari"
    },
    {
       "Title":"Chhattisgarh Police Sub Inspector Online Form 2021",
       "examComissioon":"Chhattisgarh Police Recruitment 2021",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"01/10/2021",
       "impDate2":"31/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 31/10/2021",
       "genrealFEE":"General / OBC : 400/-",
       "scstFee":"SC / ST : 200/-",
       "fee3":"Pay the Exam Fee Through Debit Card, Credit Card, Net Banking Only.",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"HP Police Constable Male / Female Online Form 2021",
       "examComissioon":"Himachal Pradesh Police Recruitment 2021",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"01/10/2021",
       "impDate2":"31/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 31/10/2021",
       "genrealFEE":"General : 300/-",
       "scstFee":"SC / ST / OBC / EWS : 150/-",
       "fee3":"All Category Female : 150/-",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"Apple IOS Apps",
       "link2":"https://itunes.apple.com/us/app/sarkari-result/id1051363935?ls=1&mt=8",
       "link3":"Click Here",
       "link4":"https://www.sarkariresults.org.in/wp-content/uploads/2021/10/Notification-for-Recruitment-of-Constables-1.pdf",
       "link5":"Click Here",
       "officialweb":"https://t.me/sarkari"
    },
    {
       "Title":"Allahabad University Assistant Professor Online Form 2021",
       "examComissioon":"University of Allahabad (AU) Teaching Post 2021",
       "subtitle":"",
       "advtNo":"Advt No. : UoA/Asst Prof/01/2021 Short Details of Notification",
       "impDate1":"28/09/2021",
       "impDate2":" 27/10/2021",
       "impdate3":"Last Date Pay Exam Fee : 27/10/2021",
       "genrealFEE":"General / OBC / EWS : 1550/-",
       "scstFee":"SC / ST : 650/-",
       "fee3":"All Category Female & PH : 50/-",
       "examName":"Allahabad University Assistant Professor in Various Subject",
       "noOfPost":"357",
       "egligible":"Master Degree in Related Subject with Minimum 55% Marks / NET / SLET / PHD.",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttrakhand Vidhan Sabha Sachivalaya Group B Or C Online Form 2021",
       "examComissioon":"Vidhan Sabha Sachivalaya, Uttrakhand ",
       "subtitle":"",
       "advtNo":"UK Sachivalaya Group B C Advt No. : 01/2021 Short Details of Notification",
       "impDate1":"01/10/2021",
       "impDate2":"",
       "impdate3":"Pay Exam Fee Last Date : 01/11/2021",
       "genrealFEE":"General / OBC : 975/-",
       "scstFee":"SC / ST : 875/-",
       "fee3":"PH (Divyang) : 150/-",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"RRC ER Various Trade Apprentice Online Form 2021.",
       "examComissioon":"Railway Recruitment Cell RRC Eastern Region (ER)",
       "subtitle":"",
       "advtNo":"RRC-ER/Act Apprentices/2020-21 Short Details of Notification",
       "impDate1":"04/10/2021",
       "impDate2":"",
       "impdate3":"Pay Exam Fee Last Date: 03/11/2021",
       "genrealFEE":"General /OBC/EWS : 100/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"Female All Category : 0/-",
       "examName":"",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Army 10+2 TES 46 January 2022 Online Form 2021",
       "examComissioon":"Join Indian Army (Bhartiya Sena) ",
       "subtitle":"",
       "advtNo":"January 2022 Course Short Details of Notification",
       "impDate1":"",
       "impDate2":"",
       "impdate3":"Admit Card Available : Notified Soon",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"No Application Fee for the All Category Candidates Only Applied the Online Form TES 43",
       "examName":"",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"Click Here",
       "link2":"https://t.me/sarkari",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttar Pradesh TET Exams UPTET 2021 Online Form",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"",
       "impDate2":"",
       "impdate3":"Pay Exam Fee Last Date : 26/10/2021",
       "genrealFEE":"For Paper I Only",
       "scstFee":"General / OBC : 600/-",
       "fee3":"SC / ST : 400/-",
       "examName":" ",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"State Bank of India SBI Various Specialist Officer SO Recruitment 2021 Online Form ",
       "examComissioon":"State Bank of India (SBI)",
       "subtitle":"",
       "advtNo":"SCO Wealth & SCO 22/15, 22/16 - 2021 Short Details of Notification",
       "impDate1":"28/09/2021",
       "impDate2":"18/10/2021",
       "impdate3":"Last Date for Pay Exam Fee : 18/10/2021",
       "genrealFEE":"General / OBC / EWS : 750/-",
       "scstFee":"SC / ST / PH: 0/-",
       "fee3":"Pay the Examination Fee Through Online Fee Mode Debit Card, Credit Card, Net Banking Only.  ",
       "examName":"Relationship Manager RM",
       "noOfPost":"126",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Veer Bahadur Singh Purvanchal University VBSPU Teaching Post Professor, Assosicate Professor & Assistant Professor Online Form 2021",
       "examComissioon":"Veer Bahadur Singh Purvanchal University, VBSPU",
       "subtitle":"",
       "advtNo":"Advt No. 01/2021 Short Details of Notification",
       "impDate1":"26/09/2021",
       "impDate2":"18/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 18/10/2021",
       "genrealFEE":"General / OBC : 1000/-",
       "scstFee":"SC / ST : 500/-",
       "fee3":"Pay the Exam Demand Draft : Finance Officer, V.B.S. Purvanchal University, Jaunpur Payble at Jaunpur.",
       "examName":"Professor",
       "noOfPost":"13",
       "egligible":"PHD Degree in Relevant Subject.",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"BPSC 67th Pre Exam Online Form 2021",
       "examComissioon":"Bihar Public Service Commission (BPSC)",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"30/09/2021",
       "impDate2":"05/11/2021",
       "impdate3":"Pay Exam Fee Last Date : 05/11/2021",
       "genrealFEE":"General / OBC/ Other State : 600/-",
       "scstFee":"SC / ST / PH : 150/-",
       "fee3":"Female Candidate (Bihar Dom.) : 150/-",
       "examName":"General",
       "noOfPost":"OBC",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Allahabad University Non Teaching Group C Various Post Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Advt No. : AUNT 04/2021 Short Details of Notification",
       "impDate1":"24/09/2021",
       "impDate2":" 23/10/2021",
       "impdate3":"Last Date Pay Exam Fee : 24/10/2021",
       "genrealFEE":"General / OBC / EWS : 1050/-",
       "scstFee":"SC / ST : 450/-",
       "fee3":"All Category Female & PH : 50/-",
       "examName":"Animal Attendant",
       "noOfPost":"05",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"SSC Selection Post IX (Phase 9) Various Post Online Form 2021",
       "examComissioon":"SSC Various Selection Post IX Recruitment 2021 Online Form",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"24/09/2021",
       "impDate2":"25/10/2021 Upto 05:00 PM Only",
       "impdate3":"Last Date Pay Exam Fee: 28/10/2021",
       "genrealFEE":"General / OBC : 100/-",
       "scstFee":"SC / ST / PH / Women : 0/-",
       "fee3":"Pay the Examination Fee Through online Debit Card, Credit Card, Net Banking or SBI E Challan Offline Mode Only",
       "examName":"Matric",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Allahabad University Non Teaching Group A & Group B Online Form 2021",
       "examComissioon":"University of Allahabad (AU) ",
       "subtitle":"",
       "advtNo":"Advt No. : AUNT 02&03/2021 Short Details of Notification",
       "impDate1":"24/09/2021",
       "impDate2":" 23/10/2021",
       "impdate3":"Last Date Pay Exam Fee : 24/10/2021",
       "genrealFEE":"General / OBC / EWS : 1050/-",
       "scstFee":"SC / ST : 450/-",
       "fee3":"All Category Female & PH : 50/-",
       "examName":"A",
       "noOfPost":"Various Group A Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"UPSC Engineering Services Pre Exam Online Form 2021",
       "examComissioon":"Union Public Service Commission (UPSC)",
       "subtitle":"",
       "advtNo":"Advt No. : 01/2022 Engg Short Details of Notification",
       "impDate1":"22/09/2021",
       "impDate2":"12/10/2021 upto 06 PM Only",
       "impdate3":"Pay Exam Fee Last Date : 12/10/2021\n",
       "genrealFEE":"General / OBC : 200/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"PH : 0/-",
       "examName":"Civil Engineering",
       "noOfPost":"",
       "egligible":"21-30 Year As on 01/01/2022",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"Click Here",
       "officialweb":"https://upsconline.nic.in/mainmenu2.php"
    },
    {
       "Title":"UPSC Geo Scientist Pre Exam Online Form 2021",
       "examComissioon":"Union Public Service Commission (UPSC)",
       "subtitle":"",
       "advtNo":"Examination Notice No.02/2022-GEOL Short Details of Notification",
       "impDate1":"",
       "impDate2":"12/10/2021upto 06:00 PM Only",
       "impdate3":"Last Date for Fee Payment : 12/10/2021",
       "genrealFEE":"General / OBC : 200/-",
       "scstFee":"SC / ST / PH : 0/- (Nil)",
       "fee3":"All Category Female : 0/- (Exempted)",
       "examName":"I",
       "noOfPost":"Geologist Group A",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://upsconline.nic.in/upsc/upload1.php",
       "link5":"Click Here",
       "officialweb":"https://upsconline.nic.in/viewapplication.php"
    },
    {
       "Title":"Indian OIL IOCL Non Executive Various Post Admit Card 2021",
       "examComissioon":"Indian Oil Corporation Ltd (IOCL) ",
       "subtitle":"",
       "advtNo":"Advt No. : 01/2021 Short Details of Notification",
       "impDate1":"21/09/2021",
       "impDate2":" 12/10/2021 upto 05 PM",
       "impdate3":"Pay Exam Fee Last Date : 12/10/2021",
       "genrealFEE":"General / OBC / EWS: 150/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"Pay the Examination Fees Through Debit Card / Credit Card / Net Banking Fees Mode Only.",
       "examName":"Post Name",
       "noOfPost":"Refinery Name",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Navy 10+2 B.Tech Entry Online Form 2021",
       "examComissioon":"Indian Navy (Join Indian Navy)",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"01/10/2021",
       "impDate2":"10/10/2021",
       "impdate3":"Last Date Send Application Form : No Need to Send Application Form",
       "genrealFEE":"All Candidates : 0/-",
       "scstFee":"No Application Fee for the All Candidates Only Fill the Online Application Form.",
       "fee3":"Only Valid JEEMAIN 2021 Score Card Candidates Are Apply Online",
       "examName":"Entry Name",
       "noOfPost":"Post Name",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://t.me/sarkari",
       "link5":"Click Here ",
       "officialweb":"https://www.joinindiannavy.gov.in/"
    },
    {
       "Title":"BSSC Mines Inspector MI Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Advt No. : 01/2021 Short Details of Notification",
       "impDate1":"20/09/2021",
       "impDate2":" 20/10/2021",
       "impdate3":"Final Submit Last Date : 22/10/2021",
       "genrealFEE":"General / OBC / EWS: 750/-",
       "scstFee":"SC / ST : 200/-",
       "fee3":"All Category Bihar Domicile Female : 200/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"Click Here",
       "officialweb":"https://bssc.bihar.gov.in/Advertisement/adv012021_2021.pdf"
    },
    {
       "Title":"Delhi RRC NR Various Trade Apprentice Online Form 2021.",
       "examComissioon":"Railway Recruitment Cell Northern Region (RRC NR)",
       "subtitle":"",
       "advtNo":"Advt No. : RRC/NR-01/2021 Short Details of Notification",
       "impDate1":"20/09/2021",
       "impDate2":" 20/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 20/10/2021",
       "genrealFEE":"General / OBC / EWS: 100/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Allahabad High Court AHC Additional Private Secretary APS Hindi / English Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"20/09/2021",
       "impDate2":"05/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 06/10/2021",
       "genrealFEE":"Gen / OBC / EWS : 1200/-",
       "scstFee":"SC / ST : 1000/-",
       "fee3":"Pay the Exam Fee Through Debit Card, Credit Card, Net Banking Only.",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"CBSE CTET December 2021 - January 2022 Online Form Date Extended",
       "examComissioon":"Central Board of Secondary Education (CBSE)",
       "subtitle":"",
       "advtNo":"CTET Dec-2021 Short Details of Notification",
       "impDate1":"",
       "impDate2":"25/10/2021",
       "impdate3":"Last Date Fee Payment : 26/10/2021",
       "genrealFEE":"General / OBC : 1000/-",
       "scstFee":"SC / ST / PH : 500/-",
       "fee3":"",
       "examName":"",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Army Short Service Commission SSC Tech 58 Men & 29 Women Online Form 2021",
       "examComissioon":"Join Indian Army (Bhartiya Sena)",
       "subtitle":"58 SSC Men & 29 SSC Women Recruitment 2021 Online Form",
       "advtNo":"April 2021 Course Short Details of Notification",
       "impDate1":"28/09/2021",
       "impDate2":"",
       "impdate3":"Last Date Complete Form : 27/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / Female : 0/-",
       "fee3":"No Application Fee for the All Candidates Only Fill the Online Application Form",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Army JAG 28th April 2022 Online Form 2021",
       "examComissioon":"Join Indian Army",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"",
       "impDate2":"28/10",
       "impdate3":"Last Date Complete Form : 28/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / Female : 0/-",
       "fee3":"No Application Fee for the All Candidates Only Fill the Online Application Form",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"UP UPPCL Assistant Accountant Exam Online Form 2021",
       "examComissioon":"Uttar Pradesh Power Corporation Limited UPPCL",
       "subtitle":"",
       "advtNo":"Advt No. : 06/VSA/2021 Short Details of Notification",
       "impDate1":"18/10/2021",
       "impDate2":"09/11/2021",
       "impdate3":"Last Date Fee Payment : 09/11/2021",
       "genrealFEE":"General / OBC / EWS : 1180/-",
       "scstFee":"SC / ST : 826/-",
       "fee3":"PH (Divyang) : 12/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here ",
       "link4":"https://cdn.digialm.com/EForms/configuredHtml/1258/73772/Instruction.html",
       "link5":"Click Here ",
       "officialweb":"https://www.youtube.com/watch?v=wdYujqcLRFM"
    },
    {
       "Title":"Uttar Pradesh UPPCL Assistant Review Officer ARO Online Form 2021",
       "examComissioon":"Uttar Pradesh Power Corporation Limited UPPCL",
       "subtitle":"",
       "advtNo":"Advt No. : 05/VSA/2021 Short Details of Notification",
       "impDate1":"18/10/2021",
       "impDate2":"09/11/2021",
       "impdate3":"Last Date Fee Payment : 09/11/2021",
       "genrealFEE":"General / OBC / EWS : 1180/-",
       "scstFee":"SC / ST : 826/-",
       "fee3":"Pay the Exam Fee Through Debit Card / Credit Card / Net Banking / E Challan",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here ",
       "link4":"https://cdn.digialm.com/EForms/configuredHtml/1258/73773/Instruction.html",
       "link5":"Click Here ",
       "officialweb":"https://www.youtube.com/watch?v=NOcXAtPQHyw"
    },
    {
       "Title":"Indian Railway Chittaranjan Locomotive Work CLW Apprentice Online Form 2021.",
       "examComissioon":"Indian Railway Chittaranjan Locomotive Work",
       "subtitle":"",
       "advtNo":"CLW Railway Apprentice Short Details of Notification",
       "impDate1":"15/09/2021",
       "impDate2":"03/10/2021",
       "impdate3":"Complete Form Last Date : 03/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Gen",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"NCRTC Various Post Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"15/09/2021",
       "impDate2":"06/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 06/10/2021",
       "genrealFEE":"General / OBC / EWS : 500/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"Pay the Examination Fee Through Debit Card, Credit Card, Net Banking or UPI, Wallet Mode Only.  ",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttar Pradesh UPPSC Technical Education Teacher Service Exam 2021 Lecturer & Other Various Post Online Form 2021.",
       "examComissioon":"Uttar Pradesh Public Service Commission (UPPSC)",
       "subtitle":"",
       "advtNo":"Advt No. : A-7/E-1/2021 Short Details of Notification",
       "impDate1":"15/09/2021",
       "impDate2":"12/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 12/10/2021",
       "genrealFEE":"General / OBC : 225/-",
       "scstFee":"SC / ST : 105/-",
       "fee3":"PH Candidates : 25/-",
       "examName":"Department Name",
       "noOfPost":"Post Name",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttar Pradesh Kheri District Aganwadi Bharti Online Form 2021.",
       "examComissioon":"Lakhimpur Kheri District Program Officer, Bal Vikas Seva Evam Pustahar Vibhag, UP",
       "subtitle":"",
       "advtNo":"Kheri District UP Aganwadi Bharti - Short Details of Notification",
       "impDate1":" 04/09/2021",
       "impDate2":"",
       "impdate3":"Complete Form Last Date : 24/09/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"No Application Fees for the All Candidates.",
       "examName":"Post Name",
       "noOfPost":"Eligibility",
       "egligible":"",
       "linkFirst":"Apple IOS Apps",
       "link2":"https://itunes.apple.com/us/app/sarkari-result/id1051363935?ls=1&mt=8",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttar Pradesh UP NHM ANM Online Form 2021.",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":": 15/09/2021 ",
       "impDate2":"",
       "impdate3":"Pay Examination Fee Last Date : 30/09/2021",
       "genrealFEE":"General / OBC / EWS : 0/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"No Application Fee for the All Candidates Only Registered Online.",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"Registration",
       "link2":"https://nhmwalkin.tsuprogram.com/",
       "link3":"Click Here",
       "link4":"https://t.me/sarkari",
       "link5":"Click Here",
       "officialweb":"http://www.upnrhm.gov.in/home/update_news_detail"
    },
    {
       "Title":"Indian Railway SECR Bilaspur Apprentice Online Form 2021",
       "examComissioon":"South East Central Railways",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"11/09/2021",
       "impDate2":"10/10/2021",
       "impdate3":"Complete Form Last Date : 10/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Gen",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Indian Navy Short Service Commission Officers SSCO Online Form 2021",
       "examComissioon":"The Indian Navy (Nausena Bharti)",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":" 21/09/2021",
       "impDate2":"05/10/2021",
       "impdate3":"Last Date Complete Form : 05/10/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST : 0/-",
       "fee3":"No Application Fee in Indian Navy SSCO Entry June 2022.",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttrakhand Teacher Eligibility Test UTET Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":"01/09/2021",
       "impDate2":"30/09/2021",
       "impdate3":"Pay Exam Fee Last Date : 30/09/2021",
       "genrealFEE":"For Paper I Only",
       "scstFee":"General / OBC / EWS: 600/-",
       "fee3":"SC / ST : 300/-",
       "examName":" ",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"Registration",
       "link2":"https://ukutet.com/instr.aspx",
       "link3":"Click Here ",
       "link4":"https://ukutet.com/uploads/docs/UTET2021Prospectus.pdf",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Chhattisgarh CGPSC Professor Online Form 2021",
       "examComissioon":"Chhattisgarh Public Service Commission (CGPSC)",
       "subtitle":"",
       "advtNo":"Advt No. : 07/2021 Short Details of Notification",
       "impDate1":" 13/09/2021",
       "impDate2":"12/10/2021",
       "impdate3":"Pay Exam Fee Last Date :12/10/2021",
       "genrealFEE":"General / Other State : 400/-",
       "scstFee":"SC / ST / OBC : 300/-",
       "fee3":"Pay the Exam Fee Through Cash at KIOSK Or Pay Debit Card, Credit Card, Net Banking Fee Mode Only",
       "examName":"Post ",
       "noOfPost":"General",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttrakhand UKPSC Assistant Engineer Online Form 2021",
       "examComissioon":"Uttrakhand Public Service Commission (UKPSC)",
       "subtitle":"",
       "advtNo":"Advt No. : A-2/E-4/A.E./2021-22 Short Details of Notification",
       "impDate1":"01/09/2021",
       "impDate2":"21/09/2021",
       "impdate3":"Last Date for Pay Exam Fee : 21/09/2021",
       "genrealFEE":"General / OBC : 276.55/-",
       "scstFee":"EWS : 276.55/-",
       "fee3":"SC / ST : 126.55/-",
       "examName":"Post Name",
       "noOfPost":"Total",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Bank of Maharashtra Specialist Officers Recruitment 2021 Online Form ",
       "examComissioon":"Bank of Maharashtra (BOM)",
       "subtitle":"",
       "advtNo":"Short Details of Notification",
       "impDate1":": 01/09/2021",
       "impDate2":"",
       "impdate3":"Pay Examination Fee : 19/09/2021",
       "genrealFEE":"General / OBC/ EWS : 1180/-",
       "scstFee":"SC / ST : 118/- ",
       "fee3":"All Category Female & PH : 0/- ",
       "examName":"Post Name",
       "noOfPost":"General",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"South Indian Bank SIB Probationary Officer PO Recruitment 2021 Online Form ",
       "examComissioon":" (SIB) ",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"01/09/2021",
       "impDate2":"08/09/2021",
       "impdate3":"Fee Payment Last Date : 08/09/2021",
       "genrealFEE":"General / OBC / EWS : 800/-",
       "scstFee":"SC / ST / PH: 800/-",
       "fee3":"Pay the Examination Fee Through Debit Card, Credit Card Or Net Banking Mode",
       "examName":"Probationary Officer PO Scale I",
       "noOfPost":"Pan India",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"NPCIL Various Trade Apprentice Online Form 2021",
       "examComissioon":"Nuclear Power Corporation of India Limited (NPCIL)",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"25/08/2021",
       "impDate2":"13/09/2021 upto 04 PM",
       "impdate3":"Complete Form Last Date : 13/09/2021",
       "genrealFEE":"General / OBC : 0/-",
       "scstFee":"SC / ST / PH : 0/-",
       "fee3":"All Category Female : 0/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Student NIELIT CCC Online Form for December 2021 Exam",
       "examComissioon":"National Institute of Electronics and Information Technology (NIELIT)",
       "subtitle":"",
       "advtNo":"DOEACC CCC Apply Online 2021 Short Details of Notification",
       "impDate1":": 01/01/2021",
       "impDate2":"",
       "impdate3":"Exam Date: Every Month",
       "genrealFEE":"General / Other State : 590/-",
       "scstFee":"OBC / BC : 590/-",
       "fee3":"SC / ST : 590/-",
       "examName":"CCC",
       "noOfPost":"No Age Limit",
       "egligible":"Any Education Qualification.",
       "linkFirst":"Click Here",
       "link2":"https://student.nielit.gov.in/CAND/CertificateRegistration.aspx?qs=XhKiZ9Tp1NEo8Y+yOzlb6G6IUX8CzY7S81jz99mCt8GPB/ixGvOPVaNggbU53Sxu",
       "link3":"Click Here ",
       "link4":"https://t.me/sarkari",
       "link5":"Click Here ",
       "officialweb":"https://www.sarkariresult.com/2021/ccc-admit-card/"
    },
    {
       "Title":"Assam Rifle Technical & Tradesman Rally Recruitment Online Form 2021",
       "examComissioon":"Assam Rifles Rally Bharti",
       "subtitle":"",
       "advtNo":"Group B & C Short Details of Notification",
       "impDate1":"11/09/2021",
       "impDate2":"25/10/2021",
       "impdate3":"Last Date Pay Exam Fee : 25/10/2021",
       "genrealFEE":"Group B Post: 200/-",
       "scstFee":"Group C Post : 100/-",
       "fee3":"Pay the Examination Fee Through Debit Card, Credit Card, Net Banking Fee Mode Only",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://drive.google.com/file/d/1V9hGIj5ejVsBuUfYrhM-D5FO9F01vv1N/view?usp=sharing",
       "link5":"Click Here",
       "officialweb":"https://www.rojgarresult.com/upload/Assam%20Rifle%20Rally%202021.jpg"
    },
    {
       "Title":"Chhattisgarh Assistant District Public Prosecution Officer ADPPO Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"Advt No. : 06/2021 Short Details of Notification",
       "impDate1":" 08/09/2021\n",
       "impDate2":"07/10/2021",
       "impdate3":"Pay Exam Fee Last Date :07/10/2021",
       "genrealFEE":"General / Other State : 400/-",
       "scstFee":"SC / ST / OBC : 300/-",
       "fee3":"Pay the Exam Fee Through Cash at KIOSK Or Pay Debit Card, Credit Card, Net Banking Fee Mode Only",
       "examName":"General",
       "noOfPost":"OBC",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Uttrakhand UKSSSC Driver Online Form 2021",
       "examComissioon":"Uttrakhand Subordinate Service Selection Commission (UKSSSC)",
       "subtitle":"",
       "advtNo":"Advt No. : 37/2021 Short Details of Notification",
       "impDate1":"27/08/2021",
       "impDate2":" 10/10/2021",
       "impdate3":"Pay Exam Fee Last Date : 12/10/2021",
       "genrealFEE":"General / OBC / EWS: 300/-",
       "scstFee":"SC / ST : 150/-",
       "fee3":"Pay the Examination Fees Through Debit Card / Credit Card / Net Banking Fees Mode Only.",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Click Here",
       "link4":"https://sssc.uk.gov.in/",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"Rajasthan RPSC Statistical Officer Online Form 2021",
       "examComissioon":"Rajasthan Public Service Commission (RPSC)",
       "subtitle":"",
       "advtNo":"Advt No. : 04/2021 Short Details of Notification",
       "impDate1":"03/09/2021",
       "impDate2":" 02/10/2021",
       "impdate3":"Last Date Pay Exam Fee : 02/10/2021",
       "genrealFEE":"General / Other State : 350/-",
       "scstFee":"OBC / BC : 250/-",
       "fee3":"SC / ST : 150/-",
       "examName":"Post Name",
       "noOfPost":"Total Post",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"Link Activate on 03/09/2021",
       "link4":"https://play.google.com/store/apps/details?id=com.app.app14f269771c01",
       "link5":"Click Here",
       "officialweb":"https://rpsc.rajasthan.gov.in/Static/RecruitmentAdvertisements/5B7DC32EB1FC42609442D06721D742AC.pdf"
    },
    {
       "Title":"RRB Ministerial and Isolated Post Stenographer Test Admit Card 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"",
       "impDate2":"",
       "impdate3":"",
       "genrealFEE":"",
       "scstFee":"",
       "fee3":"",
       "examName":"",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    },
    {
       "Title":"State Bank of India SBI Apprentice 2020 Fees Refund Online Form 2021",
       "examComissioon":"",
       "subtitle":"",
       "advtNo":"",
       "impDate1":"",
       "impDate2":"",
       "impdate3":"",
       "genrealFEE":"",
       "scstFee":"",
       "fee3":"",
       "examName":"",
       "noOfPost":"",
       "egligible":"",
       "linkFirst":"",
       "link2":"",
       "link3":"",
       "link4":"",
       "link5":"",
       "officialweb":""
    }
 ]